name: Sync Fork

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/NYU-Club-Tennis/violet-frontend.git

      - name: Fetch upstream
        run: |
          git fetch upstream
      - name: Sync develop branch
        run: |
          git checkout origin develop
          git merge upstream/develop
          git push origin develop
